### ISSUE TITLE
Using a button with Mote pHAT

### ISSUE THREAD

**Issue by russellseymour** [pimoroni/mote-phat#12]
I am trying to use a momentary switch with the Mote pHAT to control when the sticks are turned on.

I have created a simple script to test the sticks which works:

```python
import motephat

motephat.configure_channel(1, 16, False)
motephat.configure_channel(2, 16, False)

motephat.set_clear_on_exit(False)

motephat.clear()

# Set the green led
for x in range(0, 16, 2):
  motephat.set_pixel(1, x, 0, 255, 0)

# Set the red led
for x in range(0, 16, 2):
  motephat.set_pixel(2, x, 255, 0, 0)

motephat.show()
```

However when I try an combine this with the code that uses a switch, the sticks do not light up at all.

```python
# Import necessary libraries
from gpiozero import Button
import motephat
import time

# Configure variables to determine state
session_running = False

# Set the pins that are used for control
toggle_session_pin = 21

# Setup the pins
button = Button(toggle_session_pin)

# Configure the Mote LED sticks
motephat.configure_channel(1, 16, False)
motephat.configure_channel(2, 16, False)

motephat.set_clear_on_exit(False)

# Create function that starts the session
def startSession():
    global session_running

    print ("checking session")
    print (session_running)

    if session_running:
        session_running = False

        motephat.clear()      
    else:
        session_running = True

        print ("Displaying Green LEDs")

        for x in range(0, 16, 2):
            print("  setting pixel: " + str(x))
            motephat.set_pixel(1, x, 0, 255, 0)

# Detect the push button
button.when_pressed = startSession

def main():

    print ("Running program")

    while True:
        print ("Sleeping ...")
        time.sleep(1)

    # GPIO.cleanup()

if __name__ == "__main__":

    # clear any existing LEDs on the sticks
    motephat.clear()

    main()
```

I suspect that there is a clash with the GPIO that the Mote SDK is configuring and what I want to use. If this is the case, how can I cantrol the buttons as I need?

The above code works in that I get `Displaying Green LEDs` when I push the switch and it sets the `session_running` variable appropriately. However the LEDs are not activated. Is there a GPIO instance I can inherit from `motephat` that will allow me to do what I need to?

I have tried both `gpiozero` and `RPi.GPIO` and the the same problem.

**Comment by russellseymour** [comment]
As soon as I posted this I worked out what the issue was.

I was not calling `motephat.show()` after setting the LEDs in the `startSession` function.

Apologies for raising an issue without merit.

**Comment by Gadgetoid** [comment]
Hey if it solved your problem, it was worth the effort! Happy hacking.
