### ISSUE TITLE
Show() is extremely slow

### ISSUE THREAD

**Issue by jtc42** [pimoroni/mote-phat#13]
For full context: I was having issues with the LEDs taking a long time to turn on and off, flickering a lot as they were doing so, and also issues with the gamma correction. I noticed that the git repo has fixes for these so I've cloned from master and installed via setup.py.

However, the problem I'm having now is that "frame updates" take an excruciatingly long time to complete. Even using the built-in examples, rainbow.py being a great example, it updates maybe 3 times a second, where it used to be really smooth.

Have I done something daft, or is this something in the repo? I was looking for anything obvious that may cause this but I'm not sure enough to start making changes.

Thanks.

**Comment by Gadgetoid** [comment]
I think the “timing fix” might actually be a “timing break.” See: 
https://github.com/pimoroni/blinkt/issues/72

It’s clear I’ve got some updating to do here!
